#!/usr/bin/env bash
# Update the tracked exemplar at generated_systems/latest/
#
# Usage: tools/scripts/update_exemplar.sh
#
# Finds the newest folder generated by the Autocoder generator that matches
# the pattern system_YYYYMMDD_HHMMSS inside generated_systems/ and replaces
# the tracked `latest/` folder with it.  This keeps exactly one exemplar
# system under version control while allowing unlimited local runs.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
GS="$ROOT/generated_systems"

# Abort if the parent directory does not exist
if [[ ! -d "$GS" ]]; then
  echo "❌  Directory not found: $GS" >&2
  exit 1
fi

# Locate newest system_* directory
newest=$(ls -dt "$GS"/system_* 2>/dev/null | head -n 1 || true)

if [[ -z "$newest" ]]; then
  echo "⚠️  No system_* directories found under $GS" >&2
  exit 0
fi

if [[ -d "$GS/latest" ]]; then
  # If latest already points to the newest directory, do nothing.
  if [[ "$(readlink -f "$GS/latest")" == "$newest" ]]; then
    echo "✅  Exemplar already up-to-date: $(basename "$newest")"
    exit 0
  fi
  echo "🗑️  Removing old exemplar generated_systems/latest ..."
  rm -rf "$GS/latest"
fi

echo "🆕  Promoting $(basename "$newest") → generated_systems/latest"
# Copy rather than move so the timestamped folder stays for local reference
cp -R "$newest" "$GS/latest"

echo "✅  Exemplar updated.  Remember to git add generated_systems/latest/" 