# Gemini Review Configuration

# Default ignore patterns for repomix
ignore_patterns:
  - "*.pyc"
  - "__pycache__"
  - ".git"
  - ".venv"
  - "venv"
  - "node_modules"
  - "*.log"
  - ".pytest_cache"
  - "*.egg-info"
  - "build"
  - "dist"
  - "gemini-review.md"
  - "repomix-output.*"

# Documentation files to include
documentation_files:
  - "./autocoder_cc/docs/Enterprise_roadmap_v2.md"
  - "./autocoder_cc/docs/cursor_notes_2025.07121340.md"

# Claims template for critical evaluation
claims_template: |
  Previous claims made about this codebase:
  
  1. "Phase 0 foundation is mostly complete"
  2. "Centralized configuration with Pydantic Settings is implemented"
  3. "AST-based code analysis is working"
  4. "Plugin-based generator structure is in place"
  5. "Modern component architecture with anyio streams is functional"
  
  Please evaluate these claims against the actual implementation and the Enterprise Roadmap v2 requirements.