# Documentation Guard Workflow
name: doc-guard

on:
  pull_request:
    paths:
      - '**/*.md'
      - 'autocoder_cc/tools/documentation/**'
      - 'autocoder_cc/tools/config/doc_guard.yaml'
      - '.github/workflows/doc_guard.yml'

jobs:
  doc-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Documentation Guard
        run: |
          python autocoder_cc/tools/documentation/enhanced_doc_health_dashboard.py \
            --repo-root autocoder_cc \
            --config autocoder_cc/tools/config/doc_guard.yaml \
            --fail-on-critical 